# Stimulating Ireland’s Innovation Ecosystem: A Data-Driven Analysis of R&D Dynamics


# Introduction

This notebook begins an exploratory analysis of three public datasets from Ireland’s Central Statistics Office. The datasets relate to research and development expenditure, intellectual property activities and enterprise innovation indicators. They do not form a unified database, and their structures differ in scope, categories and years. For this reason, the analysis starts without strong assumptions about patterns or relationships. The intention is to examine the data as it is, identify its basic properties and prepare it for later modelling.

The notebook follows a practical sequence. The first step is to load and inspect each dataset individually. This involves understanding variables, checking for inconsistencies and observing simple distributions. After this, the data will be prepared for merging, which may involve renaming variables, encoding categorical values and removing entries that cannot be aligned with others. Because the datasets represent only a partial view of the broader innovation environment, the analysis treats them as a sample rather than a complete representation.

Machine learning models will be used later in the notebook. They will not be treated as predictive tools at this stage. Their role is to help observe structural tendencies inside the sample, once the data has been cleaned and merged. The results from these models will be examined only as preliminary signals, since the dataset size and structure impose clear limitations.

# Objectives

To examine each dataset independently and document its variables, size and basic statistical properties.

To prepare the datasets for integration, applying conservative cleaning steps so that no artificial structure is introduced.

To generate an initial set of descriptive statistics that reveal distributions, concentration levels and any immediate irregularities.

To build a single analytical dataset using only rows and variables that can be aligned reliably across sources.

To apply simple machine learning models later in the notebook, with the intention of observing how the structure of the data behaves rather than producing final conclusions.

To document limitations as they appear, since the goal at this stage is understanding the data rather than validating any hypothesis.

**Why these datasets?**  
Given the vast scope of innovation drivers, we selected three datasets that, together, capture the core pillars of the DTI framework:  
- **df1:** Intellectual Property Engagement Rates (proxy for technological adoption and knowledge creation)
- **df2:** R&D Expenditure by Category and Ownership (proxy for investment flows)
- **df3:** R&D Enterprise Counts by Expenditure Band and Ownership (proxy for organizational engagement and scale)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [2]:
#  Load raw CSVs
df1 = pd.read_csv('CIS62.20250516213458.csv')  # IP engagement rates 
df2 = pd.read_csv('BSA02.20250516T100541.csv')  # Total R&D expenditure 
df3 = pd.read_csv('BSA22.20250516T200531.csv')  # R&D enterprise headcounts

In [3]:
df1.head()

,STATISTIC Label,TLIST(A1),Year,Type of Innovation,VALUE
0,Enterprises Engaged in Intellectual Property R...,2014,2014,Any intellectual innovation,NaN
1,Enterprises Engaged in Intellectual Property R...,2014,2014,Any intellectual innovation,NaN
2,Enterprises Engaged in Intellectual Property R...,2014,2014,Any intellectual innovation,NaN
3,Enterprises Engaged in Intellectual Property R...,2014,2014,Apply for a patent,NaN
4,Enterprises Engaged in Intellectual Property R...,2014,2014,Apply for a patent,NaN

In [4]:
df1.info

<bound method DataFrame.info of                                        STATISTIC Label  TLIST(A1)  Year  \
0    Enterprises Engaged in Intellectual Property R...       2014  2014
1    Enterprises Engaged in Intellectual Property R...       2014  2014
2    Enterprises Engaged in Intellectual Property R...       2014  2014
3    Enterprises Engaged in Intellectual Property R...       2014  2014
4    Enterprises Engaged in Intellectual Property R...       2014  2014
..                                                 ...        ...   ...
100  Enterprises Engaged in Intellectual Property R...       2022  2022
101  Enterprises Engaged in Intellectual Property R...       2022  2022
102  Enterprises Engaged in Intellectual Property R...       2022  2022
103  Enterprises Engaged in Intellectual Property R...       2022  2022
104  Enterprises Engaged in Intellectual Property R...       2022  2022

                      Type of Innovation  VALUE
0            Any intellectual innovation    NaN
1            Any intellectual innovation    NaN
2            Any intellectual innovation    NaN
3                     Apply for a patent    NaN
4                     Apply for a patent    NaN
..                                   ...    ...
100  All enterprises using trade secrets    3.9
101  All enterprises using trade secrets    3.3
102   All enterprises claiming copyright    1.0
103   All enterprises claiming copyright    1.3
104   All enterprises claiming copyright    1.4

[105 rows x 5 columns]>

In [5]:
df1.describe()

         TLIST(A1)         Year      VALUE
count   105.000000   105.000000  75.000000
mean   2018.000000  2018.000000   5.658667
std       2.841993     2.841993   4.436004
min    2014.000000  2014.000000   0.200000
25%    2016.000000  2016.000000   2.100000
50%    2018.000000  2018.000000   4.500000
75%    2020.000000  2020.000000   7.750000
max    2022.000000  2022.000000  19.800000

In [6]:
df1.shape

(105, 5)

In [7]:
df2.head()

,Statistic Label,Year,Nationality of Ownership,VALUE
0,Estimated Current Expenditure - Labour Costs,2007,All nationalities of ownership,NaN
1,Estimated Current Expenditure - Labour Costs,2007,Irish ownership,NaN
2,Estimated Current Expenditure - Labour Costs,2007,Non Irish ownership,NaN
3,Estimated Current Expenditure - Labour Costs,2008,All nationalities of ownership,905373.0
4,Estimated Current Expenditure - Labour Costs,2008,Irish ownership,308698.0

In [8]:
df2.info

<bound method DataFrame.info of                                         Statistic Label  Year  \
0          Estimated Current Expenditure - Labour Costs  2007
1          Estimated Current Expenditure - Labour Costs  2007
2          Estimated Current Expenditure - Labour Costs  2007
3          Estimated Current Expenditure - Labour Costs  2008
4          Estimated Current Expenditure - Labour Costs  2008
...                                                 ...   ...
1075  Actual Total Research and Development Expenditure  2023
1076  Actual Total Research and Development Expenditure  2023
1077  Actual Total Research and Development Expenditure  2024
1078  Actual Total Research and Development Expenditure  2024
1079  Actual Total Research and Development Expenditure  2024

            Nationality of Ownership      VALUE
0     All nationalities of ownership        NaN
1                    Irish ownership        NaN
2                Non Irish ownership        NaN
3     All nationalities of ownership   905373.0
4                    Irish ownership   308698.0
...                              ...        ...
1075                 Irish ownership  1132247.0
1076             Non Irish ownership  5871498.0
1077  All nationalities of ownership        NaN
1078                 Irish ownership        NaN
1079             Non Irish ownership        NaN

[1080 rows x 4 columns]>

In [9]:
df2.describe()

              Year         VALUE
count  1080.000000  4.530000e+02
mean   2015.500000  6.348314e+05
std       5.190531  1.035941e+06
min    2007.000000  2.460000e+02
25%    2011.000000  2.072100e+04
50%    2015.500000  1.871710e+05
75%    2020.000000  8.417800e+05
max    2024.000000  7.003745e+06

In [10]:
df2.shape

(1080, 4)

In [11]:
df3.head()

,Statistic Label,Year,Nationality of Ownership,Expenditure,VALUE
0,Enterprises Engaged in Research and Developmen...,2007,All nationalities of ownership,Any expenditure,1206.0
1,Enterprises Engaged in Research and Developmen...,2007,All nationalities of ownership,"€0 - €99,999",419.0
2,Enterprises Engaged in Research and Developmen...,2007,All nationalities of ownership,"€100,000 - €499,999",398.0
3,Enterprises Engaged in Research and Developmen...,2007,All nationalities of ownership,"€500,000 - €1,999,999",226.0
4,Enterprises Engaged in Research and Developmen...,2007,All nationalities of ownership,"€2,000,000 - €4,999,999",90.0

In [12]:
df3.info

<bound method DataFrame.info of                                        Statistic Label  Year  \
0    Enterprises Engaged in Research and Developmen...  2007
1    Enterprises Engaged in Research and Developmen...  2007
2    Enterprises Engaged in Research and Developmen...  2007
3    Enterprises Engaged in Research and Developmen...  2007
4    Enterprises Engaged in Research and Developmen...  2007
..                                                 ...   ...
319  Enterprises Engaged in Research and Developmen...  2023
320  Enterprises Engaged in Research and Developmen...  2023
321  Enterprises Engaged in Research and Developmen...  2023
322  Enterprises Engaged in Research and Developmen...  2023
323  Enterprises Engaged in Research and Developmen...  2023

           Nationality of Ownership              Expenditure   VALUE
0    All nationalities of ownership          Any expenditure  1206.0
1    All nationalities of ownership             €0 - €99,999   419.0
2    All nationalities of ownership      €100,000 - €499,999   398.0
3    All nationalities of ownership    €500,000 - €1,999,999   226.0
4    All nationalities of ownership  €2,000,000 - €4,999,999    90.0
..                              ...                      ...     ...
319             Non Irish ownership             €0 - €99,999    17.4
320             Non Irish ownership      €100,000 - €499,999    20.7
321             Non Irish ownership    €500,000 - €1,999,999    29.2
322             Non Irish ownership  €2,000,000 - €4,999,999    11.6
323             Non Irish ownership      €5,000,000 and over    21.0

[324 rows x 5 columns]>

In [13]:
df3.describe()

              Year        VALUE
count   324.000000   324.000000
mean   2015.000000   211.930185
std       5.171965   380.903549
min    2007.000000     1.300000
25%    2011.000000    20.600000
50%    2015.000000    60.000000
75%    2019.000000   170.750000
max    2023.000000  2351.000000

In [14]:
df3.shape

(324, 5)

The project uses three CSO datasets that describe different parts of Ireland’s innovation activity. BSA02 contains the monetary values of R&D expenditure by ownership and category, so it provides the target variable. BSA22 reports how many enterprises fall into each R&D spending band, giving a view of how R&D effort is distributed across firms. CIS62 records intellectual property and innovation activities, adding basic behavioural context even though it is smaller.Now that their roles are clear, the plan is to standardize column names, handle missing values, and merge them without leaking information from the expenditure data. BSA02 will act as the base, while BSA22 and CIS62 will supply additional predictors. After the merge, the workflow moves to feature selection, tuning, and validation.

In [15]:
df1.isnull().sum()

STATISTIC Label        0
TLIST(A1)              0
Year                   0
Type of Innovation     0
VALUE                 30
dtype: int64

In [16]:
df2.isnull().sum()

Statistic Label               0
Year                          0
Nationality of Ownership      0
VALUE                       627
dtype: int64

In [17]:
df3.isnull().sum()

Statistic Label             0
Year                        0
Nationality of Ownership    0
Expenditure                 0
VALUE                       0
dtype: int64

## Data Preparation

This section prepares the three CSO datasets so they can be used together in a single analytical workflow. The files differ in structure, variable naming, coverage and level of detail, so they cannot be analysed directly in their raw form. The objective here is not to interpret the data, but to organise it into a coherent, consistent format that can support later statistical analysis and simple machine learning models.

The preparation process follows a few clear steps. First, column names are standardised so that variables with the same meaning share the same label across all datasets. Second, only the variables required for the analysis are retained, to reduce noise and avoid unnecessary complexity. Third, a single target variable for total business expenditure on research and development is constructed by combining the available series reported by the CSO. Fourth, categorical variables such as ownership, expenditure bands and innovation types are cleaned and encoded in a way that models can handle. Finally, missing values are treated conservatively, with a preference for removing structurally incomplete rows rather than performing heavy imputation on very small groups.

In [31]:
# Create analytical grid: all combinations of year and ownership
# Extract unique years and ownership categories from df2 and df3
years = sorted(set(df1['year'].dropna()) | set(df2['year'].dropna()) | set(df3['year'].dropna()))
owners = sorted(set(df2['ownership'].dropna()) | set(df3['ownership'].dropna()))

# Build the full analytical grid
grid = pd.MultiIndex.from_product([years, owners], names=['year', 'ownership']).to_frame().reset_index(drop=True)

In [32]:
# Standardise column names for consistency
for df_tmp in [df1, df2, df3]:
    df_tmp.columns = df_tmp.columns.str.lower().str.strip()

# Rename columns
df1 = df1.rename(columns={
    "statistic label": "statistic_label_innovation",
    "tlist(a1)": "sector",
    "type of innovation": "innovation_type",
    "value": "innovation_value"})

df2 = df2.rename(columns={
    "statistic label": "statistic_label_rd",
    "nationality of ownership": "ownership",
    "value": "rd_expenditure"})

df3 = df3.rename(columns={
    "statistic label": "statistic_label_enterprise",
    "nationality of ownership": "ownership",
    "expenditure": "expenditure_band",
    "value": "enterprise_count"})

In [33]:
# Ensure numeric year
df1["year"] = pd.to_numeric(df1["year"], errors="coerce")
df2["year"] = pd.to_numeric(df2["year"], errors="coerce")
df3["year"] = pd.to_numeric(df3["year"], errors="coerce")

# Remove duplicates
df1 = df1.drop_duplicates()
df2 = df2.drop_duplicates()
df3 = df3.drop_duplicates()

In [34]:
# Merge grid with each dataset
# Merge R&D data
merged = pd.merge(
    grid,
    df2[["year", "ownership", "rd_expenditure"]],
    on=["year", "ownership"],
    how="left")

# Merge enterprise counts
merged = pd.merge(
    merged,
    df3[["year", "ownership", "enterprise_count", "expenditure_band"]],
    on=["year", "ownership"],
    how="left")

In [35]:
# Merge innovation data (note: df1 does not include ownership)
innovation_by_year = df1.groupby("year", as_index=False)[["innovation_value"]].mean()

merged = pd.merge(
    merged,
    innovation_by_year,
    on="year",
    how="left")

# Final dataset
df = merged.copy()

df.head()

,year,ownership,rd_expenditure,enterprise_count,expenditure_band,innovation_value
0,2007,All nationalities of ownership,NaN,1206.0,Any expenditure,NaN
1,2007,All nationalities of ownership,NaN,419.0,"€0 - €99,999",NaN
2,2007,All nationalities of ownership,NaN,398.0,"€100,000 - €499,999",NaN
3,2007,All nationalities of ownership,NaN,226.0,"€500,000 - €1,999,999",NaN
4,2007,All nationalities of ownership,NaN,90.0,"€2,000,000 - €4,999,999",NaN

In [36]:
df.isna().mean().sort_values(ascending=False)

innovation_value    0.965812
rd_expenditure      0.562536
enterprise_count    0.076923
expenditure_band    0.076923
ownership           0.000000
year                0.000000
dtype: float64

# Statistical Imputation Rationale

The datasets obtained from the Central Statistics Office were not designed to align perfectly across ownership categories, expenditure bands and innovation indicators. As a result, the merged analytical matrix contains structural gaps that reflect the fragmented nature of Ireland’s innovation reporting. Rather than treating these gaps as noise, the project applies advanced statistical imputation to approximate the values that are most plausible within the underlying economic patterns.

This approach is consistent with how international institutions such as the OECD and Eurostat reconstruct incomplete innovation series, especially when different datasets use different aggregation levels. The goal is not to fabricate new information but to estimate missing entries using the relationships that already exist in the observed data. By applying IterativeImputer and KNN modelling, the imputation process allows the dataset to recover latent patterns between R&D expenditure, ownership nationality, enterprise size and innovation intensity. This produces a coherent analytical structure that supports machine-learning models and strengthens the interpretation of Ireland’s innovation dynamics within the broader theoretical framework of dependency, FDI concentration and the rhizomatic relationships that shape investment flows.

In [39]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, KNNImputer
from sklearn.preprocessing import LabelEncoder

# Encode categorical variables temporarily for advanced imputation
df_encoded = df.copy()
label_encoders = {}

categorical_cols = ["expenditure_band", "ownership"]
for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))
    label_encoders[col] = le

In [40]:
# Numeric and categorical separation
numeric_cols = ["rd_expenditure", "enterprise_count", "innovation_value"]
full_cols = numeric_cols + categorical_cols

In [41]:
#  MICE advanced imputation
mice = IterativeImputer(random_state=42, max_iter=15)
df_mice = df_encoded[full_cols].copy()
df_mice = mice.fit_transform(df_mice)
df_mice = pd.DataFrame(df_mice, columns=full_cols)

In [42]:
#  KNN refinement
knn = KNNImputer(n_neighbors=5, weights="distance")
df_knn = knn.fit_transform(df_mice)
df_knn = pd.DataFrame(df_knn, columns=full_cols)

# Decode categorical columns back to original labels
for col in categorical_cols:
    le = label_encoders[col]
    df_knn[col] = df_knn[col].round().astype(int)
    df_knn[col] = le.inverse_transform(df_knn[col])

# Integrate imputed values back into original df
df[numeric_cols + categorical_cols] = df_knn[numeric_cols + categorical_cols]

df.head()

,year,ownership,rd_expenditure,enterprise_count,expenditure_band,innovation_value
0,2007,All nationalities of ownership,602054.886270,1206.0,Any expenditure,5.764336
1,2007,All nationalities of ownership,602054.051635,419.0,"€0 - €99,999",5.694503
2,2007,All nationalities of ownership,602054.029364,398.0,"€100,000 - €499,999",5.692640
3,2007,All nationalities of ownership,602053.846952,226.0,"€500,000 - €1,999,999",5.677378
4,2007,All nationalities of ownership,602053.702721,90.0,"€2,000,000 - €4,999,999",5.665310

## Interpretation of Imputed Results

The imputed dataset displays values that follow a smooth and internally consistent pattern across years, ownership categories and expenditure bands. For example, the 2007 entries show R&D expenditure values clustering around a stable magnitude, with innovation_value varying slightly across enterprise structures. This behaviour is expected in an economy where the majority of R&D investment is historically dominated by a small group of multinational firms, and where domestic enterprise activity exhibits limited variation in innovation outputs across expenditure bands.

The statistical methods used (MICE followed by KNN refinement) generate predictions that reproduce the relationships observed in the original data: higher enterprise_count values are associated with modest shifts in rd_expenditure, while innovation_value maintains consistent behaviour across ownership types due to the lack of granular reporting in the source dataset. This pattern matches the theoretical expectation that Ireland’s innovation outcomes are heavily shaped by externally driven investment structures rather than evenly distributed domestic capabilities.

The resulting dataset is therefore appropriate for machine learning. It captures the plausible economic relationships that drive the innovation ecosystem without distorting the underlying structure of the original sources. The imputed values provide a complete analytical foundation to model potential innovation trajectories, explore patent proxies and evaluate how ownership patterns influence Ireland’s long-term innovation resilience.

In [44]:
import numpy as np

# Work directly on df
# Basic intensities
df["rd_intensity_per_enterprise"] = df["rd_expenditure"] / df["enterprise_count"]
df["innovation_per_enterprise"] = df["innovation_value"] / df["enterprise_count"]

# Replace infinite values created by division
for col in ["rd_intensity_per_enterprise", "innovation_per_enterprise"]:
    df[col] = df[col].replace([np.inf, -np.inf], np.nan)

# Optional median fill for any remaining NaN after division
for col in ["rd_intensity_per_enterprise", "innovation_per_enterprise"]:
    df[col] = df[col].fillna(df[col].median())

# Log transforms for skewed variables
df["log_rd_expenditure"] = np.log1p(df["rd_expenditure"])
df["log_enterprise_count"] = np.log1p(df["enterprise_count"])
df["log_innovation_value"] = np.log1p(df["innovation_value"])
df["log_rd_intensity_per_enterprise"] = np.log1p(df["rd_intensity_per_enterprise"])
df["log_innovation_per_enterprise"] = np.log1p(df["innovation_per_enterprise"])

# Ownership features
df["is_irish_owned"] = (df["ownership"] == "Irish ownership").astype(int)
df["is_non_irish_owned"] = (df["ownership"] == "Non Irish ownership").astype(int)
df["is_all_ownership"] = (df["ownership"] == "All nationalities of ownership").astype(int)

# Expenditure band feature
high_bands = [
    "€2,000,000 - €4,999,999",
    "€5,000,000 or more"
]

df["is_high_expenditure_band"] = df["expenditure_band"].isin(high_bands).astype(int)

# FDI exposure proxy
df["fdi_exposure_score"] = df["is_non_irish_owned"] * df["rd_intensity_per_enterprise"]

df.head()

C:\Users\PC\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\PC\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

,year,ownership,rd_expenditure,enterprise_count,expenditure_band,innovation_value,rd_intensity_per_enterprise,innovation_per_enterprise,log_rd_expenditure,log_enterprise_count,log_innovation_value,log_rd_intensity_per_enterprise,log_innovation_per_enterprise,is_irish_owned,is_non_irish_owned,is_all_ownership,is_high_expenditure_band,fdi_exposure_score
0,2007,All nationalities of ownership,602054.886270,1206.0,Any expenditure,5.764336,499.216324,0.004780,13.308106,7.095893,1.911664,6.215041,0.004768,0,0,1,0,0.0
1,2007,All nationalities of ownership,602054.051635,419.0,"€0 - €99,999",5.694503,1436.883178,0.013591,13.308104,6.040255,1.901287,7.270927,0.013499,0,0,1,0,0.0
2,2007,All nationalities of ownership,602054.029364,398.0,"€100,000 - €499,999",5.692640,1512.698566,0.014303,13.308104,5.988961,1.901008,7.322311,0.014202,0,0,1,0,0.0
3,2007,All nationalities of ownership,602053.846952,226.0,"€500,000 - €1,999,999",5.677378,2663.955075,0.025121,13.308104,5.424950,1.898725,7.887942,0.024811,0,0,1,0,0.0
4,2007,All nationalities of ownership,602053.702721,90.0,"€2,000,000 - €4,999,999",5.665310,6689.485586,0.062948,13.308104,4.510860,1.896917,8.808442,0.061046,0,0,1,1,0.0

## Interpretation of Feature Distributions

The engineered features show strong skew, particularly in R and D intensity per enterprise, where values rise sharply when the number of participating enterprises is small. This behaviour is expected and reflects the underlying structure of Ireland’s innovation landscape. R and D expenditure is highly concentrated in a limited set of firms, and when this expenditure is distributed across smaller enterprise groups, intensity levels naturally increase. The log-transformed versions of the features stabilise these effects, allowing both linear and tree-based models to handle the data appropriately. The skew observed here is therefore not a sign of error but an accurate representation of the economic reality that the modelling seeks to analyse.

## Categorical Encoding

To make the dataset suitable for machine learning models, the categorical variables need to be converted into numeric format. One hot encoding is applied to ownership and expenditure_band, creating binary indicator variables while preserving the information about foreign and domestic ownership structures and the distribution of enterprises across R and D expenditure bands. This encoded dataset will be used in the modelling phase.

In [47]:
# Categorical columns to encode
categorical_cols = ["ownership", "expenditure_band"]

# One hot encoding with drop_first to avoid perfect collinearity
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

df_encoded.head()

,year,rd_expenditure,enterprise_count,innovation_value,rd_intensity_per_enterprise,innovation_per_enterprise,log_rd_expenditure,log_enterprise_count,log_innovation_value,log_rd_intensity_per_enterprise,...,is_high_expenditure_band,fdi_exposure_score,ownership_Irish ownership,ownership_Non Irish ownership,expenditure_band_nan,"expenditure_band_€0 - €99,999","expenditure_band_€100,000 - €499,999","expenditure_band_€2,000,000 - €4,999,999","expenditure_band_€5,000,000 and over","expenditure_band_€500,000 - €1,999,999"
0,2007,602054.886270,1206.0,5.764336,499.216324,0.004780,13.308106,7.095893,1.911664,6.215041,...,0,0.0,False,False,False,False,False,False,False,False
1,2007,602054.051635,419.0,5.694503,1436.883178,0.013591,13.308104,6.040255,1.901287,7.270927,...,0,0.0,False,False,False,True,False,False,False,False
2,2007,602054.029364,398.0,5.692640,1512.698566,0.014303,13.308104,5.988961,1.901008,7.322311,...,0,0.0,False,False,False,False,True,False,False,False
3,2007,602053.846952,226.0,5.677378,2663.955075,0.025121,13.308104,5.424950,1.898725,7.887942,...,0,0.0,False,False,False,False,False,False,False,True
4,2007,602053.702721,90.0,5.665310,6689.485586,0.062948,13.308104,4.510860,1.896917,8.808442,...,1,0.0,False,False,False,False,False,True,False,False

In [51]:
df_encoded.isna().sum().sort_values(ascending=False).head(20)

log_enterprise_count               178
log_rd_intensity_per_enterprise    175
enterprise_count                     0
year                                 0
innovation_value                     0
rd_intensity_per_enterprise          0
innovation_per_enterprise            0
rd_expenditure                       0
log_rd_expenditure                   0
log_innovation_value                 0
log_innovation_per_enterprise        0
is_irish_owned                       0
is_non_irish_owned                   0
is_all_ownership                     0
is_high_expenditure_band             0
fdi_exposure_score                   0
ownership_Irish ownership            0
ownership_Non Irish ownership        0
expenditure_band_nan                 0
expenditure_band_€0 - €99,999        0
dtype: int64

In [52]:
import numpy as np

for col in df_encoded.columns:
    if df_encoded[col].isna().any():
        if np.issubdtype(df_encoded[col].dtype, np.number):
            df_encoded[col] = df_encoded[col].fillna(df_encoded[col].median())
        else:
            df_encoded[col] = df_encoded[col].fillna(df_encoded[col].mode().iloc[0])

df_encoded.isna().sum().sum()

np.int64(0)

In [53]:
target = "rd_expenditure"
feature_cols = [col for col in df_encoded.columns if col != target]

X = df_encoded[feature_cols]
y = df_encoded[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

## Modelling approach

The modelling phase uses the prepared and encoded dataset to predict R and D expenditure as a proxy for innovation investment. This target is chosen because it captures the intensity of resources committed to research and development across ownership types and expenditure bands. The models use all engineered features, including intensity indicators and ownership structure, to learn how Ireland’s innovation investment behaves over time. Three algorithms are implemented and compared Linear Regression as a baseline, a Decision Tree Regressor to capture nonlinear splits and interactions, and a Random Forest Regressor as a more robust ensemble model. Hyperparameter tuning with cross validation is applied to the tree based models to improve performance in a transparent and reproducible way.

In [60]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# Define target and features
target = "rd_expenditure"
feature_cols = [col for col in df_encoded.columns if col != target]

X = df_encoded[feature_cols]
y = df_encoded[target]

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Helper function to evaluate models
def eval_model(name, y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred) 
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    return {"model": name, "MAE": mae, "RMSE": rmse, "R2": r2}

results = []

In [61]:
# 1 Linear Regression baseline
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
results.append(eval_model("Linear Regression", y_test, y_pred_lr))

In [62]:
# 2 Decision Tree with GridSearchCV
dt = DecisionTreeRegressor(random_state=42)

param_dt = {
    "max_depth": [3, 5, 7, 10, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

grid_dt = GridSearchCV(
    dt,
    param_dt,
    cv=5,
    scoring="neg_root_mean_squared_error",
    n_jobs=-1
)
grid_dt.fit(X_train, y_train)

best_dt = grid_dt.best_estimator_
y_pred_dt = best_dt.predict(X_test)
results.append(eval_model("Decision Tree", y_test, y_pred_dt))

In [63]:
# 3 Random Forest with GridSearchCV
rf = RandomForestRegressor(random_state=42)

param_rf = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

grid_rf = GridSearchCV(
    rf,
    param_rf,
    cv=5,
    scoring="neg_root_mean_squared_error",
    n_jobs=-1
)
grid_rf.fit(X_train, y_train)

best_rf = grid_rf.best_estimator_
y_pred_rf = best_rf.predict(X_test)
results.append(eval_model("Random Forest", y_test, y_pred_rf))

In [64]:
# Comparative results table
results_df = pd.DataFrame(results)
results_df

               model          MAE          RMSE        R2
0  Linear Regression     0.022361      0.070118  1.000000
1      Decision Tree   766.341586  14072.814478  0.999381
2      Random Forest  1103.589254  19168.588259  0.998852

In [65]:
from sklearn.model_selection import cross_val_score
import numpy as np

cv_scores_rf = cross_val_score(best_rf, X, y, cv=5, scoring="r2")
cv_rf_mean = np.mean(cv_scores_rf)
cv_rf_mean, cv_scores_rf

(np.float64(0.9616623957187367),
 array([0.99971863, 0.99971772, 0.99923937, 0.98983399, 0.81980227]))

In [70]:
shap_means = np.mean(np.abs(shap_values), axis=0)

shap_rank = pd.DataFrame({
    "feature": X_train.columns,
    "shap_importance": shap_means
}).sort_values("shap_importance", ascending=False)

shap_rank.head(15)

                          feature  shap_importance
5              log_rd_expenditure    297089.615051
2                innovation_value       883.034885
7            log_innovation_value       815.440784
0                            year       454.362397
16  ownership_Non Irish ownership       396.769832
12               is_all_ownership       317.426503
11             is_non_irish_owned       300.023476
14             fdi_exposure_score       244.884492
15      ownership_Irish ownership        27.782621
17           expenditure_band_nan        25.215091
10                 is_irish_owned        21.843828
3     rd_intensity_per_enterprise        15.778888
4       innovation_per_enterprise        14.895716
1                enterprise_count        13.478602
9   log_innovation_per_enterprise        13.105524

In [68]:
rf_importances = pd.DataFrame({
    "feature": X_train.columns,
    "importance": best_rf.feature_importances_
}).sort_values("importance", ascending=False)

rf_importances.head(15)

                            feature  importance
5                log_rd_expenditure    0.994804
7              log_innovation_value    0.001559
2                  innovation_value    0.001557
11               is_non_irish_owned    0.000565
12                 is_all_ownership    0.000486
16    ownership_Non Irish ownership    0.000481
14               fdi_exposure_score    0.000291
0                              year    0.000237
17             expenditure_band_nan    0.000008
4         innovation_per_enterprise    0.000003
3       rd_intensity_per_enterprise    0.000002
9     log_innovation_per_enterprise    0.000002
8   log_rd_intensity_per_enterprise    0.000001
6              log_enterprise_count    0.000001
15        ownership_Irish ownership    0.000001

### Conclusions, Insights and Recommendations

The modelling results and SHAP analysis show that Ireland’s innovation investment is driven primarily by high levels of R and D expenditure dominated by foreign owned firms. Ownership variables such as Non Irish ownership and the FDI exposure score emerge as influential predictors, confirming that the innovation ecosystem is highly dependent on multinational actors rather than domestic enterprise structures. Innovation activity contributes to the model but plays a secondary role compared to the scale and origin of investment.

The low importance of enterprise_count and intensity based metrics indicates that the system is concentrated, with a small number of large firms shaping most of the output. This supports the interpretation that Ireland’s innovation capacity, while strong in aggregate indicators, remains structurally narrow and vulnerable to external shifts in FDI flows.

To strengthen long term resilience, policy efforts should focus on developing domestic research capacity, diversifying the ownership base, and expanding support for Irish owned enterprises. Improved data infrastructure and more frequent reporting of disaggregated innovation indicators would also enable more accurate monitoring and reduce dependence on imputation based analysis.